ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 125
  resolution: 64
  scale: 8
  r: 1
  ect_type: "points"
  ambient_dimension: 3
  normalized: True
  chunk_size: 32

ectlossconfig: &ref-ectlossconfig
  seed: 2024
  num_thetas: 125
  resolution: 64
  scale: 8
  r: 1
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

transform:

data:
  module: datasets.protein
  root_dir: /home/aromanowski/IPT-Equivariant-VAE/data/protein
  raw_dir: /home/aromanowski/IPT-Equivariant-VAE/data/protein/processed
  num_workers: 2
  batch_size: 32
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

trainer: &ref-trainer
  module: trainer
  seed: 1111
  max_epochs: 500
  log_every_n_steps: 1
  accelerator: gpu
  precision: "32-true"
  checkpoint_interval: 50

modelconfig:
  module: models.equiv_vae
  num_pts: 512
  lr: 0.0001    
  latent_channels: 32  
  beta_min:    0.0     
  beta_max:    0.0001   
  beta_period: 300            
  l_max: 4 
  sh_input_channels: 64
  im_channels: 1
  disc_start: 0
  disc_weight: 0.0
  perceptual_weight: 0.0
  latent_dim: 0
  ectlossconfig: *ref-ectlossconfig
  ectconfig: *ref-ectconfig

logger:
  module: loggers.wandblogger
  project: shape-synthesis
  entity: aidos-labs
  trainconfig: *ref-trainer
  results_dir: equivariant_vae_protein
# ectconfig: &ref-ectconfig
#   seed: 2024
#   num_thetas: 125
#   resolution: 20
#   scale: 128
#   r: 7
#   ect_type: "points"
#   ambient_dimension: 3
#   normalized: True
#   chunk_size: 32

# ectlossconfig: &ref-ectlossconfig
#   num_thetas: 64
#   resolution: 64
#   scale: 8
#   r: 7
#   ect_type: "points"
#   ambient_dimension: 3
#   normalized: True
#   seed: 2024

# transform:

# data:
#   module: datasets.protein
#   root_dir: /home/aromanowski/IPT-Equivariant-VAE/data/protein
#   raw_dir: /home/aromanowski/IPT-Equivariant-VAE/data/protein/processed
#   num_workers: 2
#   batch_size: 128
#   pin_memory: True
#   drop_last: False
#   force_reload: False
#   ectconfig: *ref-ectconfig

# trainer: &ref-trainer
#   module: trainer
#   seed: 1111
#   max_epochs: 50
#   log_every_n_steps: 1
#   accelerator: gpu
#   precision: null
#   checkpoint_interval: 1000

# modelconfig:
#   module: models.equiv_vae
#   num_pts: 512
#   lr: 0.001
#   l_max: 4
#   latent_channels: 16
#   sh_input_channels: 20
#   beta_period: 100
#   beta_min: 0.001
#   beta_max: 1.0
#   im_channels: 1
#   disc_start: 0
#   disc_weight: 0.0
#   perceptual_weight: 0.0
#   latent_dim: 0      
#   ectlossconfig: *ref-ectlossconfig
#   ectconfig: *ref-ectconfig

# logger:
#   module: loggers.wandblogger
#   project: shape-synthesis
#   entity: aidos-labs
#   trainconfig: *ref-trainer
#   results_dir: equivariant_vae_protein
